### ISSUE TITLE
Show message as a notification if the app runs?

### ISSUE THREAD

**Issue by e-alfred** [fds2610/NCT-Desktop#7]
It would be nice to have the messages shown as a notification (like other messenger apps) instead of just showing a green icon if a new message was received.

**Comment by fds2610** [comment]
@e-alfred thanks for your idea. Does your linux-version only show a green icon instead of a bubble-notification? in my windows the green icon does only indicate that the tool was able to connect to nextcloud server and communicate (http-response=200). if the icon gets blue there was a timeout or an http-error.

**Comment by fds2610** [comment]
please open a bug if the functionality does not work like the one described in the wiki...

**Comment by e-alfred** [comment]
It looks like this:

![tray](https://user-images.githubusercontent.com/10073629/79197699-7aaf6100-7e32-11ea-9913-0f461424f6d7.png)

I cannot see any tray notification showing the last message received.
