### ISSUE TITLE
Better windows 10 notifications integration

### ISSUE THREAD

**Issue by Refhi** [fds2610/NCT-Desktop#9]
When we receive a notification on windows 10 it last about 7 sec then totally diseappear.

If I right clic on the notification (in the deployed windows notification panel) before it diseappear I can access the "notification and action" configuration pannel, but NCT-Desktop is nowhere to be seen.

I suspect it has something to do with it not being fully installed within windows ?

Anyway could we get lasting notifications ? (I'm a doctor so if I have a notification while taking care of someone it would be nice if it where still here when I come back to my computer)

thanks for your work !

**Comment by fds2610** [comment]
Hello @refhi thanks for using this tool and giving feedback. I know that notification currently does not work perfect due to an API bug in the used libraries. I added the function to change the icon whenever a new notification arrives. I just uploaded the binary for windows so you can use this.
during the last days i realised that this red bubble does not disappear anymore, so i will have to add this functionality later, but maybe it is now better, than your version. please kee me informed.

**Comment by Refhi** [comment]
Thanks

I might be mistaken but downloading code.schepmann.de/NCT-Desktop/nct-desktop-win32-ia32.zip still gives me the 0.06v, is that to be expected ?

the "N" logo seems to work though but stays on after a notification

**Comment by fds2610** [comment]
Hi @Refhi yes, this is actually expected behavior. I am working on a workaround.

**Comment by fds2610** [comment]
uploaded new version 0.0.7 with previous notification method only for win32 platforms.
works nice for me in Win10/64bit - any other platform tests welcome. will close this in a couple of days if no one documents a veto, here :-)

**Comment by Refhi** [comment]
Works perfectly here in windows 10 (I'll try to test other platform if I have time)

**Comment by fds2610** [comment]
thanks for testing !
